"""
Availability Module — Queries team availability and calculates available slots.

Encapsulates the logic for consulting Google Calendar's FreeBusy API,
generating candidate 30-minute slots within business hours (Mon-Fri, 9:00-17:00),
filtering out slots that overlap with busy periods from any team calendar,
excluding past slots for today's date, and formatting the results as a
numbered list for the user.
"""

import datetime
from zoneinfo import ZoneInfo

from validators import (
    validate_date,
    is_business_day,
    slots_overlap,
)

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

SLOT_DURATION_MINUTES = 30
BUSINESS_START_HOUR = 9
BUSINESS_START_MINUTE = 0
BUSINESS_END_HOUR = 17
BUSINESS_END_MINUTE = 0

# Error messages (Spanish, matching design document)
ERROR_WEEKEND = (
    "La fecha seleccionada cae en fin de semana. "
    "Las reuniones se agendan únicamente de lunes a viernes."
)
ERROR_NO_SLOTS = (
    "No hay horarios disponibles para la fecha {date}. "
    "¿Te gustaría consultar otra fecha?"
)


# ---------------------------------------------------------------------------
# Slot generation
# ---------------------------------------------------------------------------


def generate_candidate_slots(
    date: datetime.date,
    timezone_str: str,
) -> list[tuple[datetime.datetime, datetime.datetime]]:
    """
    Generate 16 candidate slots of 30 minutes aligned to :00 and :30
    within business hours (9:00–17:00) in the configured timezone.

    Start times range from 9:00 to 16:30, each producing a 30-minute slot.

    Args:
        date: The date for which to generate slots.
        timezone_str: IANA timezone string (e.g. "America/Mexico_City").

    Returns:
        List of (start, end) tuples as timezone-aware datetimes.
    """
    tz = ZoneInfo(timezone_str)
    slots: list[tuple[datetime.datetime, datetime.datetime]] = []

    current = datetime.datetime(
        date.year, date.month, date.day,
        BUSINESS_START_HOUR, BUSINESS_START_MINUTE,
        tzinfo=tz,
    )
    end_of_day = datetime.datetime(
        date.year, date.month, date.day,
        BUSINESS_END_HOUR, BUSINESS_END_MINUTE,
        tzinfo=tz,
    )
    delta = datetime.timedelta(minutes=SLOT_DURATION_MINUTES)

    while current + delta <= end_of_day:
        slots.append((current, current + delta))
        current += delta

    return slots


# ---------------------------------------------------------------------------
# Slot filtering
# ---------------------------------------------------------------------------


def filter_available_slots(
    candidate_slots: list[tuple[datetime.datetime, datetime.datetime]],
    busy_periods: dict[str, list[dict]],
    now: datetime.datetime | None = None,
) -> list[tuple[datetime.datetime, datetime.datetime]]:
    """
    Filter candidate slots by removing those that overlap with any busy
    period from any calendar, and those whose start time has already passed.

    Args:
        candidate_slots: Slots generated by ``generate_candidate_slots``.
        busy_periods: Mapping of calendar email → list of busy dicts,
            each with ``"start"`` and ``"end"`` ISO 8601 strings.
        now: If provided, slots whose start time is before *now* are excluded.

    Returns:
        List of available (start, end) tuples.
    """
    available: list[tuple[datetime.datetime, datetime.datetime]] = []

    # Flatten and parse all busy periods from all calendars
    parsed_busy: list[tuple[datetime.datetime, datetime.datetime]] = []
    for _email, periods in busy_periods.items():
        for period in periods:
            busy_start = datetime.datetime.fromisoformat(period["start"])
            busy_end = datetime.datetime.fromisoformat(period["end"])
            parsed_busy.append((busy_start, busy_end))

    for slot_start, slot_end in candidate_slots:
        # Exclude past slots
        if now is not None and slot_start < now:
            continue

        # Check overlap with any busy period from any calendar
        is_busy = False
        for busy_start, busy_end in parsed_busy:
            if slots_overlap(slot_start, slot_end, busy_start, busy_end):
                is_busy = True
                break

        if not is_busy:
            available.append((slot_start, slot_end))

    return available


# ---------------------------------------------------------------------------
# Response formatting
# ---------------------------------------------------------------------------


def format_slots_response(
    slots: list[tuple[datetime.datetime, datetime.datetime]],
    timezone_str: str,
) -> str:
    """
    Format available slots as a numbered list with HH:MM 24-hour format.

    Example output::

        1. 09:00 - 09:30
        2. 11:00 - 11:30

    Args:
        slots: List of (start, end) timezone-aware datetimes.
        timezone_str: IANA timezone for display.

    Returns:
        Formatted string with one line per slot.
    """
    tz = ZoneInfo(timezone_str)
    lines: list[str] = []
    for i, (start, end) in enumerate(slots, start=1):
        local_start = start.astimezone(tz)
        local_end = end.astimezone(tz)
        lines.append(
            f"{i}. {local_start.strftime('%H:%M')} - {local_end.strftime('%H:%M')}"
        )
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Orchestrator
# ---------------------------------------------------------------------------


def check_availability(
    date_str: str,
    calendar_service,
    team_calendars: list[str],
    timezone_str: str,
) -> tuple[int, str]:
    """
    Orchestrate the full availability check for a given date.

    Steps:
        1. Validate the date string.
        2. Check that the date is a business day.
        3. Call the FreeBusy API for all team calendars.
        4. Generate candidate slots.
        5. Filter available slots (excluding busy and past slots).
        6. Format and return the response.

    Args:
        date_str: Date in YYYY-MM-DD format.
        calendar_service: Authenticated Google Calendar API service instance.
        team_calendars: List of team member email addresses.
        timezone_str: IANA timezone string.

    Returns:
        Tuple of (status_code, response_message).
    """
    # 1. Validate date
    valid, error_msg, parsed_date = validate_date(date_str)
    if not valid:
        return (200, error_msg)

    # 2. Check business day
    if not is_business_day(parsed_date):
        return (200, ERROR_WEEKEND)

    # 3. Build FreeBusy request
    tz = ZoneInfo(timezone_str)
    time_min = datetime.datetime(
        parsed_date.year, parsed_date.month, parsed_date.day,
        BUSINESS_START_HOUR, BUSINESS_START_MINUTE,
        tzinfo=tz,
    )
    time_max = datetime.datetime(
        parsed_date.year, parsed_date.month, parsed_date.day,
        BUSINESS_END_HOUR, BUSINESS_END_MINUTE,
        tzinfo=tz,
    )

    freebusy_body = {
        "timeMin": time_min.isoformat(),
        "timeMax": time_max.isoformat(),
        "timeZone": timezone_str,
        "items": [{"id": email} for email in team_calendars],
    }

    freebusy_response = (
        calendar_service.freebusy().query(body=freebusy_body).execute()
    )

    # 4. Extract busy periods per calendar
    busy_periods: dict[str, list[dict]] = {}
    for email in team_calendars:
        busy_periods[email] = freebusy_response["calendars"][email]["busy"]

    # 5. Generate candidate slots
    candidate_slots = generate_candidate_slots(parsed_date, timezone_str)

    # 6. Filter available slots
    today = datetime.datetime.now(tz).date()
    now_param = datetime.datetime.now(tz) if parsed_date == today else None
    available_slots = filter_available_slots(
        candidate_slots, busy_periods, now=now_param,
    )

    # 7. Format response
    if not available_slots:
        return (200, ERROR_NO_SLOTS.format(date=date_str))

    formatted = format_slots_response(available_slots, timezone_str)
    return (200, formatted)
